# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpliftEd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
