# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpliftEd', '0003_auto_20170128_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='thumbnail',
            field=models.CharField(max_length=128),
        ),
    ]
