# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpliftEd', '0005_auto_20170128_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='rep_index',
            field=models.IntegerField(),
        ),
    ]
